### ISSUE TITLE
No match found for majority of tracks

### ISSUE THREAD

**Issue by SMores** [rckclmbr/pyportify#89]
Seems to be completely unable to find most tracks for some reason. It's also inconsistent in which tracks it finds, e.g. in two runs of importing the same playlist (16 tracks total), the first time 6 tracks were found, and the second time a **different** 2 tracks were found.

**Comment by SMores** [comment]
As another example: when trying to import Saved Tracks, each of two runs found about 300 sounds (out of a total of 1,500 or something), and there was a 50-song overlap in what they were able to find. It seems like this might be a throttling issue. Also seems like this isn't just me: #90

**Comment by SMores** [comment]
Did a bit of poking around:

Setting the semaphore's starting value to 1 didn't seem to have any effect whatsoever.

Looking at the actual responses from the failed searches, Google is returning a search response with status 200 and no sign of throttling. So unless they're being weirdly opaque about their throttling, it seems like something else might be the cause.

**Comment by knarf1** [comment]
I am having the same problem.  Nothing found on a playlist of 80 tracks (New Music Friday if someone wants to try to replicate) - all but 78 tracks found when searching GPM manually.  Worked flawlessly for months for me prior to this.

**Comment by SMores** [comment]
Adding some retry logic seemed to fix this for me, though inexplicably one (and seemingly only one) of my playlists now completely fails. If this continues working and the root cause isn't identified, I can open a small PR

**Comment by cordell** [comment]
are you going to submit a pull request?

**Comment by dakial** [comment]
I'm getting this problem also. Is there a "for dummies" fix for this or should I wait for an official fix?

**Comment by cordell** [comment]
SMores has said he will submit a pull request, allowing us to add the fix into the repo.  Once it is merged it will be much easier if you have no knowledge of "git"

**Comment by rckclmbr** [comment]
This should be fixed in the latest release, let me know how it goes.

**Comment by knarf1** [comment]
Much appreciated, and much better than it was!  I tried the "New Indie Mix" playlist.   Found matches for 93 out of the 101 (didn't go through line by line to see if they all matched accurately, but the first 20 or so did).

The tracks below came back as "no match found" for whatever reason, although I could find them in Google Play with a manual search.

Super Whatevr - Benjamin Alphabet
The Cactus Channel - Sorry Hills
Wilderado - Talking About Love To A Cigarette
Bayonne - Fallss
Sampha - Kora Sings

I don't know what's different about these tracks that would cause them to not match when all the others did. Hopefully this information helps if you decide to tweak it further.  Just glad to see it working again.

**Comment by dakial** [comment]
Just tested it and the main problem seems to be solved. There are some missing songs still (as knarf1 pointed above) but it must be just a problem of not being a perfect match (spelling, name, file size, etc..). A different issue.

**Comment by dakial** [comment]
@rckclmbr Apparently the problem is back with this version (0.3.13), just tried it again with my wife's account and got 0 matches for all the songs.
I'm attaching the log just in case.
[portify.txt](https://github.com/rckclmbr/pyportify/files/802415/portify.txt)

**Comment by rckclmbr** [comment]
@dakial you still having issues?  It's working fine for me.

**Comment by dakial** [comment]
@rckclmbr Yes, still. But I don't have the premium account anymore. Maybe that is the problem?

**Comment by oscar704** [comment]
am using trial google play music at the moment, unlimited (same thing as all access?) but still have no matches when trying to import playlists from spotify
